from typing import Protocol

from neeka.brain.event import Event
from neeka.brain.project import Project
from neeka.brain.task import Task
from neeka.brain.user import User


class UserRepository(Protocol):
    def save(self, user: User) -> None: ...
    def get(self, user_id: str) -> User | None: ...
    def list(self) -> list[User]: ...


class ProjectRepository(Protocol):
    def save(self, project: Project) -> None: ...
    def get(self, project_id: str) -> Project | None: ...
    def list(self) -> list[Project]: ...
    def add_member(self, project_id: str, user_id: str, role: str) -> None: ...
    def has_member(self, project_id: str, user_id: str) -> bool: ...


class TaskRepository(Protocol):
    def save(self, task: Task) -> None: ...
    def get(self, task_id: str) -> Task | None: ...
    def list(self) -> list[Task]: ...
    def add_dependency(self, task_id: str, depends_on_id: str) -> None: ...


class EventRepository(Protocol):
    def append(self, event: Event) -> None: ...
    def list(self) -> list[Event]: ...