from __future__ import annotations

from typing import Protocol

from ..artifact import Artifact
from ..relationships import ArtifactRelationship
from ..version import ArtifactVersion as ArtifactVersionEntity


class ArtifactRepository(Protocol):
    def save(self, artifact: Artifact, version: ArtifactVersionEntity) -> None: ...
    def get(self, artifact_id: str) -> Artifact | None: ...
    def list(self, project_id: str) -> list[Artifact]: ...
    def versions(self, artifact_id: str) -> list[ArtifactVersionEntity]: ...
    def find_checksum(self, project_id: str, checksum: str) -> list[Artifact]: ...
    def delete(self, artifact_id: str, updated_at: str) -> None: ...
    def add_relationship(self, relationship: ArtifactRelationship) -> None: ...
    def relationships(self, artifact_id: str) -> list[ArtifactRelationship]: ...
    def remove_relationship(self, relationship: ArtifactRelationship) -> None: ...
    def artifacts_for_target(self, target_type: str, target_id: str) -> list[Artifact]: ...
