from typing import Protocol

from ..decision import Decision
from ..document import Document, DocumentVersion
from ..note import Note
from ..project_knowledge import ProjectKnowledge
from ..reference import Reference
from ..requirement import Requirement


class KnowledgeRepository(Protocol):
    def save_document(self, document: Document, version: DocumentVersion) -> None: ...
    def get_document(self, document_id: str) -> Document | None: ...
    def list_documents(self, project_id: str) -> list[Document]: ...
    def list_document_versions(self, document_id: str) -> list[DocumentVersion]: ...
    def save_requirement(self, requirement: Requirement) -> None: ...
    def list_requirements(self, project_id: str) -> list[Requirement]: ...
    def save_decision(self, decision: Decision) -> None: ...
    def list_decisions(self, project_id: str) -> list[Decision]: ...
    def save_note(self, note: Note) -> None: ...
    def list_notes(self, project_id: str) -> list[Note]: ...
    def save_reference(self, reference: Reference) -> None: ...
    def list_references(self, project_id: str) -> list[Reference]: ...
    def get_project_knowledge(self, project_id: str) -> ProjectKnowledge: ...
    def search(self, project_id: str, keyword: str, type: str | None = None, status: str | None = None) -> list[dict]: ...
    def add_relationship(self, source_type: str, source_id: str, relationship: str, target_type: str, target_id: str) -> None: ...
    def relationships(self, source_type: str, source_id: str) -> list[dict]: ...
